services:
  streamlit:
    build: .
    container_name: my_streamlit_site
    ports:
      - "8501:8501"
    volumes:
      - /root/dbt:/mnt/host_dbt
      - ~/.ssh:/root/.ssh:ro                    # geef je SSH key mee
      - ~/.gitconfig:/root/.gitconfig:ro        # neem gitconfig over
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
